### ISSUE TITLE
Cannot launch Pachira

### ISSUE THREAD

**Issue by NoData02939** [taihuapp/Pachira#1]
When running the .exe it echos "Pachira.jar not found" I have installed both javas to the correct level, restarted the computer, and edited the path to FX, I have retyped the java launch command seperate to verify it was a seperate issue and attempted to launch the java file on its own. all result in the same issue. 
Windows 10 x64
Java FX level 11.0.2
Java Level 11, I have tried newer and older version of Java, and Java FX.

**Comment by NoData02939** [comment]
After further digging it was due to "-jar %~dp0%Pachira.jar" and "if not exist %~dp0%Pachira.jar (
  echo Pachira.jar not found
  pause
  exit /b 1"

I removed "%~dp0%" from both lines and the program is now running properly so far.

**Comment by NoData02939** [comment]
New issue, upon importing the CSV its skipping all lines, even after altering CSV to handle the appropriate names and date locations. skips all lines, imports 0

**Comment by taihuapp** [comment]
Sorry for the delay.  Are you importing prices or transactions in CSV?

**Comment by taihuapp** [comment]
When you unpacked the zip file, where do you keep the content?  Do you have
the runPachira.bat in the same folder as the Pachira.jar?  The %~dp0% is
there so the .bat file will locate the Pachira.jar in the same folder.

I just tried the unmodified runPachira.bat file on my own windows 10
machine without any problem.
